name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)" >> $GITHUB_ENV

      - name: Deploy Frontend
        if: ${{ env.CHANGED_FILES }} && contains(env.CHANGED_FILES, 'frontend/')
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: echo "Frontend changes detected, deploying frontend"

      - name: SSH Deploy Frontend
        if: ${{ env.CHANGED_FILES }} && contains(env.CHANGED_FILES, 'frontend/')
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << 'EOF'
            cd /var/www && rm -rf dist
            cd /root/core/meatIsland/frontend
            git pull
            npm install
            npm run build
            mv /root/core/meatIsland/frontend/dist /var/www
            sudo systemctl restart nginx
          EOF

      - name: Deploy Backend
        if: ${{ env.CHANGED_FILES }} && contains(env.CHANGED_FILES, 'backend/')
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: echo "Backend changes detected, deploying backend"

      - name: SSH Deploy Backend
        if: ${{ env.CHANGED_FILES }} && contains(env.CHANGED_FILES, 'backend/')
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << 'EOF'
            cd /root/core/meatIsland/backend
            git pull
            npm install
            npm run build
            NODE_ENV=production pm2 start --name APP_NAME npm -- start
          EOF
